blank_issues_enabled: false
contact_links:
  - name: Support and Questions
    about: Do not open issues for questions, instead visit our support section.
    url: https://github.com/olivr-com/defaults/blob/master/docs/CONTRIBUTING.md
